#https://github.com/haproxy-ingress/charts/blob/master/haproxy-ingress/README.md#configuration
controller:
  #config:
  #  use-proxy-protocol: "true"
#  tcp:
#    50051: kube-ops/cuckoofilter:50051
  replicaCount: 1
  service:
    type: LoadBalancer #ClusterIP
    #externalTrafficPolicy: Local
    #loadBalancerIP: 52.130.178.125
    httpPorts:
    - port: 80
      targetPort: http
    httpsPorts:
    - port: 443
      targetPort: https
#    extraPorts:
#    - port: 22
#      targetPort: 22
defaultBackend:
  enabled: true
  image:
    repository: qiuguobin/defaultbackend
