apiVersion: apps/v1
kind: Deployment
metadata:
  name: eba-doc
  namespace: kube-ops
spec:
  replicas: 1
  selector:
    matchLabels:
      name: eba-doc
  template:
    metadata:
      labels:
        name: eba-doc
    spec:
      containers:
      - name: eba-doc
        image: stagingacr.azurecr.cn/eba-doc:latest
        ports:
        - containerPort: 6060
---
apiVersion: v1
kind: Service
metadata:
  name: eba-doc
  namespace: kube-ops
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 6060
    targetPort: 6060
  selector:
    name: eba-doc
