apiVersion: apps/v1
kind: Deployment
metadata:
  name: target-tracking-api
  namespace: kube-ops
spec:
  replicas: 1
  selector:
    matchLabels:
      name: target-tracking-api
  template:
    metadata:
      labels:
        name: target-tracking-api
    spec:
      containers:
      - name: api
        image: stagingacr.azurecr.cn/target-tracking-api-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 7878
        envFrom:
        - secretRef:
            name: azure-env
        env:
        - name: TZ
          value: Asia/Shanghai
---
apiVersion: v1
kind: Service
metadata:
  name: target-tracking-api
  namespace: kube-ops
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 7878
    targetPort: 7878
  selector:
    name: target-tracking-api
