apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-dind-target-tracking
  namespace: kube-ops
  labels:
    app: docker-dind-target-tracking
spec:
  selector:
    matchLabels:
      app: docker-dind-target-tracking
  template:
    metadata:
      labels:
        app: docker-dind-target-tracking
    spec:
      containers:
      - image: docker:dind
        name: docker-dind-target-tracking
        args:
        - --registry-mirror=https://ot2k4d59.mirror.aliyuncs.com/
        env:
        - name: DOCKER_DRIVER
          value: overlay2
        - name: DOCKER_HOST
          value: tcp://0.0.0.0:2375
        - name: DOCKER_TLS_CERTDIR
          value: ""
        volumeMounts:
        - name: data
          mountPath: /var/lib/docker/
        ports:
        - name: daemon-port
          containerPort: 2375
        securityContext:
          privileged: true
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: pvc-docker-dind-target-tracking
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-docker-dind-target-tracking
  namespace: kube-ops
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: managed-premium
  resources:
    requests:
      storage: 500Gi
---
apiVersion: v1
kind: Service
metadata:
  name: docker-dind-target-tracking
  namespace: kube-ops
  labels:
    app: docker-dind-target-tracking
spec:
  ports:
  - port: 2375
    targetPort: 2375
  selector:
    app: docker-dind-target-tracking
