apiVersion: apps/v1
kind: Deployment
metadata:
  name: target-tracking-kpi-lan
  namespace: kube-ops
spec:
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  replicas: 1
  selector:
    matchLabels:
      name: target-tracking-kpi-lan
  template:
    metadata:
      labels:
        name: target-tracking-kpi-lan
    spec:
      containers:
      - name: target-tracking-kpi-lan
        image: stagingacr.azurecr.cn/target-tracking-kpiengine:latest
        ports:
        - containerPort: 7879
        env:
        - name: TZ
          value: Asia/Shanghai
        - name: EVENTHUB_ENDPOINT
          value: "Endpoint=sb://ce2-cndgt-evh-np-cvc.servicebus.chinacloudapi.cn/;SharedAccessKeyName=authrule_coupon_lancome;SharedAccessKey=VA8lGxdOYVAtrRMb0VCg7g6Ox9wdtDSWbeAyFnot2HA=;EntityPath=coupon_lancome"
        volumeMounts:
        - name: data
          mountPath: /data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: pvc-target-tracking-lan
---
apiVersion: v1
kind: Service
metadata:
  name: target-tracking-kpi-lan
  namespace: kube-ops
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 7879
    targetPort: 7879
  selector:
    name: target-tracking-kpi-lan
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-target-tracking-lan
  namespace: kube-ops
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: managed-premium
  resources:
    requests:
      storage: 100Gi
