apiVersion: apps/v1
kind: Deployment
metadata:
  name: target-tracking-facade
  namespace: kube-ops
spec:
  replicas: 1
  selector:
    matchLabels:
      name: target-tracking-facade
  template:
    metadata:
      labels:
        name: target-tracking-facade
    spec:
      containers:
      - name: target-tracking-facade
        image: stagingacr.azurecr.cn/target-tracking-facade:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: target-tracking-facade
  namespace: kube-ops
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: 8080
  selector:
    name: target-tracking-facade
