apiVersion: apps/v1
kind: Deployment
metadata:
  name: accountservice
  namespace: kube-ops
spec:
  replicas: 1
  selector:
    matchLabels:
      name: accountservice
  template:
    metadata:
      labels:
        name: accountservice
    spec:
      containers:
      - name: accountservice
        image: stagingacr.azurecr.cn/accountservice:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 7777
        envFrom:
        - secretRef:
            name: azure-env
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
---
apiVersion: v1
kind: Service
metadata:
  name: accountservice
  namespace: kube-ops
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: 7777
  selector:
    name: accountservice
