apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: kube-ops
  labels:
    app: mysql
data:
  my.cnf: |-
    [client]
    default-character-set=utf8mb4
    [mysql]
    default-character-set=utf8mb4
    [mysqld]
    max_connections=200
    character_set_server=utf8mb4
