apiVersion: apps/v1
kind: Deployment
metadata:
  name: obtracking-debug-prometheus
  namespace: kube-ops
spec:
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  replicas: 1
  selector:
    matchLabels:
      name: obtracking-debug-prometheus
  template:
    metadata:
      labels:
        name: obtracking-debug-prometheus
    spec:
      containers:
      - name: prometheus
        image: prom/prometheus
        ports:
        - containerPort: 9090
        volumeMounts:
        - name: config
          mountPath: /etc/prometheus/prometheus.yml
          subPath: prometheus.yml
      volumes:
      - name: config
        configMap:
          name: obtrackig-debug-prometheus-configmap
---
apiVersion: v1
kind: Service
metadata:
  name: obtracking-debug-prometheus
  namespace: kube-ops
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 9090
    targetPort: 9090
  selector:
    name: obtracking-debug-prometheus
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: obtrackig-debug-prometheus-configmap
  namespace: kube-ops
data:
  prometheus.yml: |-
    global:
      scrape_interval:     15s
      evaluation_interval: 15s

    rule_files:
      # - "first.rules"
      # - "second.rules"

    scrape_configs:
      - job_name: prometheus
        static_configs:
          - targets: ['localhost:9090']
      - job_name: myapp
        scrape_interval: 10s
        static_configs:
        - targets:
          - obtracking-debug:2112
