apiVersion: apps/v1
kind: Deployment
metadata:
  name: obtracking-debug
  namespace: kube-ops
spec:
#  strategy:
#    rollingUpdate:
#      maxSurge: 0
#      maxUnavailable: 1
#    type: RollingUpdate
  replicas: 1
  selector:
    matchLabels:
      name: obtracking-debug
  template:
    metadata:
      labels:
        name: obtracking-debug
    spec:
      containers:
      - name: obtracking-debug
        image: stagingacr.azurecr.cn/obtracking-debug:latest
        ports:
        - containerPort: 6060
        env:
        - name: TZ
          value: Asia/Shanghai
        volumeMounts:
        - name: data
          mountPath: /data
#      volumes:
#      - name: data
#        hostPath:
#          path: /data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: pvc-obtracking-debug
---
#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: pvc-obtracking-debug
#  namespace: kube-ops
#spec:
#  accessModes:
#  - ReadWriteOnce
#  storageClassName: managed-premium
#  resources:
#    requests:
#      storage: 5Gi
---
#apiVersion: v1
#kind: Service
#metadata:
#  name: obtracking-debug
#  namespace: kube-ops
#spec:
#  type: ClusterIP
#  ports:
#  - name: http
#    port: 2112
#    targetPort: 2112
#  selector:
#    name: obtracking-debug
---
apiVersion: v1
kind: Service
metadata:
  name: obtracking-debug-doc
  namespace: kube-ops
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 6060
    targetPort: 6060
  selector:
    name: obtracking-debug
