apiVersion: apps/v1
kind: Deployment
metadata:
  name: coupon-tools-backend
  namespace: kube-ops
spec:
  replicas: 1
  selector:
    matchLabels:
      name: coupon-tools-backend
  template:
    metadata:
      labels:
        name: coupon-tools-backend
    spec:
      containers:
      - name: coupon-tools-backend
        image: stagingacr.azurecr.cn/coupon-tools-backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 9006
        envFrom:
        - secretRef:
            name: azure-env
        env:
        - name: TZ
          value: Asia/Shanghai
---
apiVersion: v1
kind: Service
metadata:
  name: coupon-tools-backend
  namespace: kube-ops
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: 9006
  selector:
    name: coupon-tools-backend
